header = 'ply' 'format' 'ascii' '1.0'

list_def = 'list' TYPE TYPE NAME

scalar_def = TYPE NAME

property = 'property' (list_def | scalar_def)

element = 'element' NAME INT { property }

file = header { element } END_HEADER
